version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app:${APP_VERSION:-latest}
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: always
    volumes:
      - .:/app/src/
    env_file:
      - .env
    labels:
      # Enable traefik for this container
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`${APP_TRAEFIK_HOST:-app.localhost}`)
      - traefik.http.routers.app.entrypoints=http
      - traefik.http.routers.app.service=app
      - traefik.http.services.app.loadbalancer.server.port=8000
    networks:
      - traefik-shared
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_HOST: ${APP_HOST:-0.0.0.0}
      APP_DB_HOST: ${APP_DB_HOST:-db}
      APP_DB_PORT: ${APP_DB_PORT:-5432}
      APP_DB_USER: ${APP_DB_USER:-app}
      APP_DB_PASS: ${APP_DB_PASS:-app}
      APP_DB_BASE: ${APP_DB_BASE:-app}

  db:
    image: postgres:16.3-bullseye
    hostname: ${APP_DB_HOST_NAME:-db}
    environment:
      POSTGRES_USER: ${APP_DB_USER:-app}
      POSTGRES_PASSWORD: ${APP_DB_PASS:-app}
      POSTGRES_DB: ${APP_DB_BASE:-app}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USER:-app}"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db-data:
    name: db-data

networks:
  traefik-shared:
    name: traefik-shared
